# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'finedustAPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for finedustAPI
	pod 'Alamofire'
  target 'finedustAPITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'finedustAPIUITests' do
    # Pods for testing
  end

end
